#!/bin/sh -e

# Copyright (C) 2023, John Clark <inindev@gmail.com>

# kernel post-remove hook: /etc/kernel/postrm.d
# script to delete the specified dtb file from
# /boot after a kernel is package removed

version="$1"
target="/boot/rk3568-odroid-m1.dtb-${version}"

# passing the kernel version is required
if [ -z "${version}" ]; then
	echo >&2 "W: dtb_rm: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

echo "cleaning up ${target}"
rm -f "${target}"

