#!/bin/sh -e

# Copyright (C) 2023, John Clark <inindev@gmail.com>

# kernel post-install hook: /etc/kernel/postinst.d
# script to copy the specified dtb file to /boot
# after a new kernel is package installed

version="$1"
source="/usr/lib/linux-image-${version}/rockchip/rk3568-odroid-m1.dtb"
target="/boot/rk3568-odroid-m1.dtb-${version}"

# passing the kernel version is required
if [ -z "${version}" ]; then
	echo >&2 "W: dtb_copy: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

if [ ! -f "${source}" ]; then
	echo >&2 "W: dtb_copy: ${source} not found"
	exit 3
fi

echo "installing ${source} to ${target}"
install -m 644 "${source}" "${target}"

